export const tasks = [
 { title:'Montere bunnsvill', description:'Svillen beveger seg ned til underlaget. Festepunktene vises etter plassering. Dette er en illustrasjon uten angitte avstander.', phase:['Plasser svillen','Se festepunktene','Bunnsvillen er vist på plass'], detail:'Festepunkt i bunnsvillen', detailDescription:'Snittet viser et symbolsk festemiddel som beveger seg gjennom treverket og ned i underlaget. Forankring i betong og tre krever ulike dokumenterte løsninger.' },
 { title:'Montere stendere', description:'Stenderne flyttes inn én om gangen. Rekkefølgen viser delene pedagogisk; nødvendig avstiving og faktisk byggemetode må avklares separat.', phase:['Plasser stenderne','Se forbindelsene nederst','Stenderne er vist på plass'], detail:'Forbindelse ved stenderfoten', detailDescription:'Et symbolsk festemiddel beveger seg på skrå ved stenderfoten. Dette er ingen anbefaling om skruing eller vinkel; forbindelsen må følge valgt løsning.' },
 { title:'Montere toppsvill', description:'Toppsvillen senkes til stenderne. Markeringene viser hvor forbindelser må avklares, uten å spesifisere festemidler.', phase:['Plasser toppsvillen','Se forbindelsene øverst','Toppsvillen er vist på plass'], detail:'Forbindelse ved toppsvillen', detailDescription:'Snittet viser et symbolsk festemiddel gjennom en svill og mot en stender. Faktisk feste, retning og lengde bestemmes av konstruksjonen.' },
 { title:'Vindusåpning', description:'Se sidefeltene, losholtene og de korte stenderne rundt en illustrert vindusåpning. Overstykket er ikke en dimensjonert bjelke.', phase:['Plasser delene rundt åpningen','Se forbindelsene','Vindusåpningen er vist'], detail:'Forbindelse ved losholt', detailDescription:'Bevegelsen illustrerer forbindelsen mellom en horisontal del og en sidestender. Bærende åpninger krever prosjekterte løsninger.' },
 { title:'Døråpning', description:'Se sidestenderne og overstykket rundt en illustrert døråpning. Bunnsvillen er allerede delt i modellen for å holde åpningen fri; kapping er ikke animert.', phase:['Plasser delene rundt døren','Se forbindelsene','Døråpningen er vist'], detail:'Forbindelse over døråpningen', detailDescription:'Et symbolsk festemiddel viser en forbindelse ved overstykket. Illustrasjonen viser ikke dimensjonert bæring eller dokumentert innfesting.' }
];
export function partProgress(progress,index,count){const t=Math.max(0,Math.min(1,(progress/.72)*(1+(count-1)*.22)-index*.22));return t*t*(3-2*t);}
export function phaseIndex(progress){return progress>=1?2:progress>=.72?1:0;}
export function validateTask(value){return Number.isInteger(value)&&value>=0&&value<tasks.length;}
